### ISSUE TITLE
Uncaught Error: Could not find module ember-typeahead-input/typeahead-input

### ISSUE THREAD

**Issue by odix67** [namlook/ember-typeahead-input#1]
Hi, I'm a bit lost, I've tried to test this addon, but endet up with the error
`Uncaught Error: Could not find module ember-typeahead-input/typeahead-input`

using ember-cli 0.1.15 ember.js 1.8.1

the same happens if I clone this repo, install dependencies and start the server

BR

**Comment by namlook** [comment]
thanks for the bug report :grinning:

**Comment by odix67** [comment]
thanks for the fast fix, but now I've got
`Uncaught TypeError: Cannot read property 'length' of undefined`
in the jquery code, I've tested also your implementation, adapted to my JSON and also tested a "twitter" json, with no success.

any suggestions ?

BR

**Comment by namlook** [comment]
well, it works fine for me. Can you post a snippet that produce the error ?

**Comment by ServiceTo** [comment]
This is old, but I just fixed that problem myself, so leaving a breadcrumb here in case someone else finds it.  (Cost me over a day in bug hunting)

The problem is that the default use of this addon has a filter so instead of listening for 

```
[{"name": "value","name2":"value2"}]
```

like normal typeahead.js the `filterData` function is picking out `data.results` so you can change that function or make your json respond with: 

```
{"results":[{"name": "value","name2":"value2"}]}
```

and it will just work.
